version: "3.9"

networks:
  external_net:
  internal_net:

secrets:
  accountant_db_database:
    file: secrets/db_database.txt
  accountant_db_password:
    file: secrets/db_password.txt
  accountant_db_root_password:
    file: secrets/db_root_password.txt
  accountant_db_user:
    file: secrets/db_user.txt

services:
  # GO app
  app:
    build:
      context: ./app
      target: dev
    container_name: accountant_app
    # Despite this container depending on the DB it still produces dial up errors since it spins up faster.
    # Just wait a bit until the DB container is up and running and the errors are going to stop.
    # TODO: Find a way to eliminate these errors altogether.
    depends_on:
      - database
    environment:
      DB_NAME: /run/secrets/accountant_db_database
      DB_PASSWORD: /run/secrets/accountant_db_password
      DB_USER: /run/secrets/accountant_db_user
    image: accountant_app
    networks:
      - external_net
      - internal_net
    secrets:
      - accountant_db_database
      - accountant_db_password
      - accountant_db_user
    restart: on-failure
  # MySQL database
  database:
    container_name: accountant_database
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/accountant_db_database
      MYSQL_PASSWORD_FILE: /run/secrets/accountant_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/accountant_db_root_password
      MYSQL_USER_FILE: /run/secrets/accountant_db_user
    image: mysql
    networks:
      - internal_net
    ports:
      - "3306:3306"
    restart: always
    secrets:
      - accountant_db_database
      - accountant_db_password
      - accountant_db_root_password
      - accountant_db_user
    volumes:
      - db_vol:/var/lib/mysql
  # Nginx reverse proxy
  nginx:
    build:
      context: ./nginx
      target: dev
    container_name: accountant_nginx
    depends_on:
      - app
    image: accountant_nginx
    networks:
      - external_net
    ports:
    - "80:80"
    restart: always
    volumes:
      - nginx_assets_vol:/var/www/devexp.co/assets
  redis:
    container_name: accountant_redis
    image: redis:alpine
    networks:
      - internal_net
    volumes:
      - redis_vol:/data

volumes:
  db_vol:
  nginx_assets_vol:
    driver: local
    driver_opts:
      device: $PWD/app/assets
      o: bind
      type: none
  redis_vol:
