version: "3.9"

services:
  # Let's Encrypt certificates.
  cert:
    build: ./cert
    container_name: accountant_cert
    depends_on:
      - nginx
    image: accountant_cert
    networks:
      - internal_net
    volumes:
      - cert_challenge_vol:/var/www/cert
      - cert_vol:/etc/letsencrypt
  nginx:
    build:
      #args:
      #  - HTTP_PASSWORD=http_password
      #  - HTTP_USER=http_user
      context: ./nginx
      target: prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert_challenge_vol:/var/www/cert
      - cert_vol:/etc/letsencrypt
      #- auth_vol:/etc/nginx/auth

volumes:
  #auth_vol:
  cert_challenge_vol:
  cert_vol:
