version: "3.9"

services:
  app:
    build:
      args:
        GOARG: -gcflags='all=-N -l'
    env_file:
      - app/env.dev
    # Debugger.
    ports:
      - "2345:2345"
    security_opt:
      - seccomp:unconfined
    volumes:
      - app_templates_vol:/app/templates
  redis:
    ports:
      - "6379:6379"

volumes:
  app_templates_vol:
    driver: local
    driver_opts:
      device: $PWD/app/templates
      o: bind
      type: none
