version: "3.9"

services:
  app:
    volumes:
      - app_vol:/app
  redis:
    ports:
      - "6379:6379"

volumes:
  app_vol:
    driver: local
    driver_opts:
      device: $PWD/app
      o: bind
      type: none
