base_url:
cache:
  database: 0
  host: redis
  password:
  port: 6379
  username:
database:
  host: database
  name: accountant
  password:
  port: 3306
  root_password:
  root_username:
  username:
development:
mail:
  default_sender:
  host:
  password:
  port:
  username:
session:
  cookie_name: "accountant-session"
  key_prefix: "session"
  secure_cookie:
