framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://accountant_redis
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: devexp/accountant
