twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        format_date: 'd. m. Y'
    form_themes:
        - 'form/tailwind_3.html.twig'
when@test:
    twig:
        strict_variables: true
